# Generated by Django 4.1.7 on 2023-09-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
