# Generated by Django 4.1.7 on 2023-09-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0008_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAlumni',
            fields=[
                ('nim', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('nohp', models.IntegerField()),
                ('thnlulus', models.IntegerField(max_length=4)),
                ('prodi', models.CharField(max_length=255)),
                ('instansi', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='static/assets/img')),
            ],
        ),
    ]
