# Generated by Django 4.1.7 on 2023-09-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataalumni',
            name='thnlulus',
            field=models.IntegerField(),
        ),
    ]
