# Generated by Django 4.1.7 on 2023-09-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_dataalumni_thnlulus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataAlumni',
        ),
    ]
