# Generated by Django 4.1.7 on 2023-09-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_dataalumni_nohp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataalumni',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images'),
        ),
    ]
