# Generated by Django 4.1.7 on 2023-09-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_pengumuman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
