# Generated by Django 4.1.7 on 2023-09-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_pengumuman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengumuman',
        ),
    ]
