# Generated by Django 4.1.7 on 2023-09-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_pengumuman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('idpengumuman', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('namapengumuman', models.CharField(max_length=255)),
                ('datepengumuman', models.DateField()),
                ('deskripsipengumuman', models.CharField(max_length=500)),
                ('filepengumuman', models.FileField(blank=True, null=True, upload_to='static/assets/file')),
            ],
        ),
    ]
