# Generated by Django 4.1.7 on 2023-10-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_loker'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataalumni',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
