# Generated by Django 4.1.7 on 2023-10-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_dataalumni_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataalumni',
            name='diajukan',
            field=models.BooleanField(default=False),
        ),
    ]
