# Generated by Django 4.1.7 on 2023-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_dataalumni_diajukan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='idagenda',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
