# Generated by Django 4.1.7 on 2023-10-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_agenda_idagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengumuman',
            name='idpengumuman',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
