# Generated by Django 4.1.7 on 2023-10-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_pengumuman_idpengumuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loker',
            name='idloker',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
