# Generated by Django 4.1.7 on 2023-10-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_bincangalumni_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bincangalumni',
            name='date',
        ),
    ]
