# Generated by Django 4.1.7 on 2023-10-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_bincangalumni_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BincangAlumni',
        ),
    ]
