# Generated by Django 4.1.7 on 2023-10-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='bincangalumni',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bincangalumni'),
        ),
    ]
