# Generated by Django 4.1.7 on 2023-10-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_bincangalumni_reply_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
