# Generated by Django 4.1.7 on 2023-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataalumni',
            name='grup',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
