# Generated by Django 4.1.7 on 2023-10-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_dataalumni_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataalumni',
            name='facebook',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataalumni',
            name='instagram',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
